# yamllint disable rule:line-length
# yamllint disable rule:indentation
# yamllint disable rule:comments-indentation
# too many spelling things, spell-checker: disable

- module-name: 'WLEDLipSync'
  data-files:
    - dirs:
        - 'rhubarb/win'
      patterns:
        - '*.*'
      when: 'win32'
    - dirs:
        - 'rhubarb/linux'
      patterns:
        - '*.*'
      when: 'linux'
    - dirs:
        - 'rhubarb/mac'
      patterns:
        - '*.*'
      when: 'macos'
  dlls:
    - from_filenames:
      relative_path: 'rhubarb/win'
      executable: 'yes'
    - from_filenames:
      relative_path: 'rhubarb/mac'
      executable: 'yes'
      when: 'macos'
    - from_filenames:
      relative_path: 'rhubarb/linux'
      executable: 'yes'
      when: 'linux'

