# yamllint disable rule:line-length
# yamllint disable rule:indentation
# yamllint disable rule:comments-indentation
# too many spelling things, spell-checker: disable

- module-name: 'WLEDLipSync.py'
  data-files:
    - dirs:
        - './rhubarb/win'
        - './rhubarb/win/res'
        - './rhubarb/win/res/sphinx'
        - './rhubarb/win/res/sphinx/acoustic-model'
      patterns:
        - '**'
      when: 'win32'
    - dirs:
        - 'rhubarb/linux'
        - 'rhubarb/linux/res'
        - 'rhubarb/linux/res/sphinx'
        - 'rhubarb/linux/res/sphinx/acoustic-model'
      patterns:
        - '**'
      when: 'linux'
    - dirs:
        - 'rhubarb/mac'
        - 'rhubarb/mac/res'
        - 'rhubarb/mac/res/sphinx'
        - 'rhubarb/mac/res/sphinx/acoustic-model'
      patterns:
        - '**'
      when: 'macos'
  dlls:
    - from_filenames:
      relative_path: './rhubarb/win'
      prefixes: '**'
      executable: 'yes'
      when: 'win32'
    - from_filenames:
      prefixes: '**'
      relative_path: 'rhubarb/mac'
      executable: 'yes'
      when: 'macos'
    - from_filenames:
      prefixes: '**'
      relative_path: 'rhubarb/linux'
      executable: 'yes'
      when: 'linux'

